### ISSUE TITLE
Fold coverage report by pytest-cov

### ISSUE THREAD

**Issue by thedrow** [abusalimov/pytest-travis-fold#2]
If pytest-cov is installed and enbaled, allow to fold the coverage report in travis.

**Comment by abusalimov** [comment]
I've thought of that recently. Though I'm not sure whether this should be implemented within pytest-travis-fold or in pytest-cov. I'll see what I can do.

**Comment by abusalimov** [comment]
Upgrade to v1.2.0 to catch up this feature.

**Comment by thedrow** [comment]
thanks!
